# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtervalue',
            name='key',
            field=models.CharField(choices=[('server_name', 'server name'), ('logger', 'logger'), ('site', 'site')], max_length=32),
        ),
        migrations.AlterField(
            model_name='groupedmessage',
            name='logger',
            field=models.CharField(blank=True, db_index=True, default='root', max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='logger',
            field=models.CharField(blank=True, db_index=True, default='root', max_length=64),
        ),
        migrations.AlterField(
            model_name='messagefiltervalue',
            name='key',
            field=models.CharField(choices=[('server_name', 'server name'), ('logger', 'logger'), ('site', 'site')], max_length=32),
        ),
    ]
