# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-22 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0002_auto_20200605_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupedmessage',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
